### ISSUE TITLE
Does FlaUI works on .Net core?

### ISSUE THREAD

**Issue by bawarim** [Roemer/FlaUI#238] opened 2019-04-19 05:29 UTC
I have created my automation framework in .Net core. Now I need to use FlaUI in my framework to automate the desktop apps. 
So I would like to know if it can work with .Net core or not. If yes then how can i use it in my dot net core project.

When I am running it on dotnet core platform then it gives below error. 

Message: System.TypeLoadException : Could not load type 'Interop.UIAutomationClient.IUIAutomation' from assembly 'Interop.UIAutomationClient, Version=12.0.20617.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

**Comment by Roemer** [comment] 2019-04-19 11:22
I did a PoC here: https://github.com/Roemer/FlaUI/issues/141#issuecomment-365401082
Give it a try. I plan on rewrite it a bit to support .Net standard in the near future.

**Comment by bawarim** [comment] 2019-04-19 11:37
Tried but not working. Getting the same error.

**Comment by Roemer** [comment] 2019-04-19 11:45
Do you have a smaple project you could upload or share?

**Comment by bawarim** [comment] 2019-04-19 12:06
Please see attached project. 

[AutomationSolution.zip](https://github.com/Roemer/FlaUI/files/3098034/AutomationSolution.zip)

**Comment by bawarim** [comment] 2019-04-23 05:15
@Roemer did u get a chance to look into this?

**Comment by Roemer** [comment] 2019-04-24 20:30
For some reason, the Interop.UIAutomationClient.dll is not copied to the output (note that you have another file, Interp.UIAutomationClient.dll, which is the wrong one). Copy the correct file from the FlaUI.UIA3.2.0.0-alpha4.nupkg to the output and it should work.

**Comment by bawarim** [comment] 2019-04-25 07:26
Thanks @Roemer.
It worked. You are right Interop.UIAutomationClient.dll is not copying to the output folder. When i copied it manually, its working.

**Comment by bawarim** [comment] 2019-05-03 09:00
Hi @Roemer 

I can see that currently FlaUI.Core.Capturing is not available in 2.0.0-alpha4 version. 
I need to take screenshot for my .Net core project. 
So is there any plan to add these libraries in dotnet core supported version as well?

**Comment by bawarim** [comment] 2019-06-24 05:18
Hi @Roemer,
Is there any update regarding FlaUI.Core.Capturing?

**Comment by Roemer** [comment] 2019-10-17 15:36
I just ported Capturing to .netstandard, I am continue working on core compatibility. Not many errors left actually :)

**Comment by Roemer** [comment] 2019-10-31 13:19
Duplicate of #141

**Closed by Roemer** 2019-10-31 13:19 UTC
