### ISSUE TITLE
AutomationElement is missing UnregisterStructureChangedEventHandler

### ISSUE THREAD

**Issue by MT-PL-SWF-Dev** [Roemer/FlaUI#213] opened 2018-10-22 10:11 UTC
The AutomationElement contains method for registering the structure changed event handled, but doesn't have the one for unregistering it.

I had a look into the code and it seems that those methods are only proxying to the underlying FrameworkAutomationElement. What brings me to another question - could this design be simplified? Does it make sense to have a logical differentiation between AutomationElement and FrameworkAutomation element? Have you considered that the specific AutomationElements inherit from the FrameworkAutomationElement (and then instead of passing around the FrameworkAutomationElementBase, pass the automation and native element)? If this could be possible, then there would be no need for the proxy methods anymore.

**Comment by Roemer** [comment] 2019-11-08 06:57
I see your point. But I did not find a good way to achieve this.
The problem is that the `AutomationElement` should not be abstract so it can easily be instanciated. On the other way, there are many properties and methods that cannot be implemented in the `AutomationElement` because they need the concrete UIA framework. I will look some more for a design pattern that works. If not, I will add an interface with the register/unregister methods so that there is at least a compilation error in case one is forgotten when a new one is added :)

**Comment by Roemer** [comment] 2019-11-08 13:45
I've added the interfaces. On a side note, the event handlers do not need to be unregistered from the `AutomationElement`. This is taken care of automatically when an `EventHandler` is disposed. I've added a small wiki page: https://github.com/Roemer/FlaUI/wiki/Events
I'll close this issue as that should cover everything. Otherwise feel free to re-open it.

**Closed by Roemer** 2019-11-08 13:45 UTC
